### ISSUE TITLE
`tabsWithNumbers` doesn't work with search editors

### ISSUE THREAD

**Issue by Ilanaya** [zardoy/vscode-experiments#24]
Search editor has associated number but focusing command doesn't work

**Comment by zardoy** [comment]
> Search editor has associated number

The main issue is that it doesn't as it doesn't seem to be a text editor.

https://github.com/zardoy/vscode-experiments/blob/258073ecf681e4bd74b4642e786ab69a82aa4fb6/src/features/tabsWithNumbers.ts#L74

Currently we get the tab index in non-filtered array, thats why we don't skip tabs, in which we can't display the number.
It's possible to fix to fix this in two ways:

- leave counting as is (while skiping some stabs) and use different focusing approach:

Replace whole `focusTabFromLeft` func https://github.com/zardoy/vscode-experiments/blob/258073ecf681e4bd74b4642e786ab69a82aa4fb6/src/features/tabsWithNumbers.ts#L14 with `await vscode.commands.executeCommand('workbench.action.openEditorAtIndex', index)`

- correct counting number: add in `focusTabFromLeft` and `provideFileDecoration` `.filter` before `.findIndex`, it should fix.

**Comment by zardoy** [comment]
@ILScc you decide.
